package com.mca.econsult.service;

import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;

@Service
public class ReportService {

    @Value("${report.output-dir}")
    private String outputDir;

    /**
     * Generate a PDF report with analysis results.
     *
     * @param username       the user who generated the report
     * @param totalComments  total number of comments analyzed
     * @param positivePct    positive percentage
     * @param neutralPct     neutral percentage
     * @param negativePct    negative percentage
     * @param uncertainCount number of uncertain predictions
     * @param summaries      map of sentiment -> summary text
     * @param policyStatus   the final decision status
     * @return path to the generated PDF
     */
    public String generateReport(String username, int totalComments,
                                  double positivePct, double neutralPct, double negativePct,
                                  int uncertainCount, Map<String, String> summaries,
                                  String policyStatus) {
        try {
            String outputPath = outputDir + "report.pdf";
            File outputFile = new File(outputPath);
            outputFile.getParentFile().mkdirs();

            PdfWriter writer = new PdfWriter(outputPath);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);

            // Title
            Paragraph title = new Paragraph("MCA eConsultation - Sentiment Analysis Report")
                    .setFontSize(22)
                    .setBold()
                    .setFontColor(new DeviceRgb(0, 51, 102))
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(5);
            document.add(title);

            // Subtitle
            Paragraph subtitle = new Paragraph("Ministry of Corporate Affairs")
                    .setFontSize(14)
                    .setFontColor(new DeviceRgb(100, 100, 100))
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20);
            document.add(subtitle);

            // Meta info
            String dateStr = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMMM yyyy, HH:mm"));
            document.add(new Paragraph("Generated by: " + username).setFontSize(11));
            document.add(new Paragraph("Date: " + dateStr).setFontSize(11).setMarginBottom(15));

            // Divider
            document.add(new LineSeparator(new com.itextpdf.kernel.pdf.canvas.draw.SolidLine())
                    .setMarginBottom(15));

            // Final Decision Highlight
            document.add(new Paragraph("PROPOSED POLICY STATUS: " + policyStatus)
                    .setFontSize(14).setBold()
                    .setFontColor(ColorConstants.WHITE)
                    .setBackgroundColor(new DeviceRgb(0, 51, 102))
                    .setPadding(10)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(15));

            // Summary Statistics
            document.add(new Paragraph("Summary Statistics")
                    .setFontSize(16).setBold().setFontColor(new DeviceRgb(0, 51, 102))
                    .setMarginBottom(10));

            Table statsTable = new Table(UnitValue.createPercentArray(new float[]{1, 1, 1, 1, 1}))
                    .useAllAvailableWidth()
                    .setMarginBottom(20);

            statsTable.addHeaderCell(createHeaderCell("Total Comments"));
            statsTable.addHeaderCell(createHeaderCell("Positive %"));
            statsTable.addHeaderCell(createHeaderCell("Neutral %"));
            statsTable.addHeaderCell(createHeaderCell("Negative %"));
            statsTable.addHeaderCell(createHeaderCell("Uncertain"));

            statsTable.addCell(createDataCell(String.valueOf(totalComments)));
            statsTable.addCell(createDataCell(String.format("%.1f%%", positivePct)));
            statsTable.addCell(createDataCell(String.format("%.1f%%", neutralPct)));
            statsTable.addCell(createDataCell(String.format("%.1f%%", negativePct)));
            statsTable.addCell(createDataCell(String.valueOf(uncertainCount)));

            document.add(statsTable);

            // AI-Generated Summaries
            document.add(new Paragraph("AI-Generated Summaries")
                    .setFontSize(16).setBold().setFontColor(new DeviceRgb(0, 51, 102))
                    .setMarginBottom(10));

            if (summaries != null) {
                for (Map.Entry<String, String> entry : summaries.entrySet()) {
                    String sentimentLabel = entry.getKey().substring(0, 1).toUpperCase() + entry.getKey().substring(1);
                    document.add(new Paragraph(sentimentLabel + " Feedback:")
                            .setFontSize(12).setBold().setMarginBottom(3));
                    document.add(new Paragraph(entry.getValue())
                            .setFontSize(10).setMarginBottom(10));
                }
            }


            document.close();
            return outputPath;
        } catch (Exception e) {
            String msg = e.getMessage() != null ? e.getMessage() : e.toString();
            throw new RuntimeException("Failed to generate PDF report: " + msg, e);
        }
    }

    private Cell createHeaderCell(String text) {
        return new Cell()
                .add(new Paragraph(text).setBold().setFontSize(10))
                .setBackgroundColor(new DeviceRgb(0, 51, 102))
                .setFontColor(ColorConstants.WHITE)
                .setTextAlignment(TextAlignment.CENTER)
                .setPadding(5);
    }

    private Cell createDataCell(String text) {
        return new Cell()
                .add(new Paragraph(text).setFontSize(10))
                .setTextAlignment(TextAlignment.CENTER)
                .setPadding(5);
    }
}
