spring.application.name=econsultation
logging.level.com.mca=DEBUG
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Storage Paths
file.upload-dir=${UPLOAD_PATH:./uploads/}
report.output-dir=${REPORT_PATH:./src/main/resources/static/}

# AI Service Configuration
ai.service.url=${AI_SERVICE_URL:https://aksh053712-mca-ai-api.hf.space}

# Storage Paths
upload.path=${UPLOAD_PATH:./uploads/}
output.path=${OUTPUT_PATH:./src/main/resources/static/}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.user-name-attribute=name
